name: Deploy MedVault Backend to EC2

on:
  push:
    branches: [ "master" ] # Make sure this is your main branch!

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          # 1. Go to the correct project folder
          cd ~/MedVault 
          
          # 2. Pull the latest code
          git pull origin master  # Change 'master' to 'main' if your branch is named 'main'
          
          # 3. Stop and remove the old container (using sudo)
          sudo docker stop medvault || true
          sudo docker rm medvault || true
          
          # 4. Build the new image (using sudo)
          sudo docker build -t medvault .
          
          # 5. Run the new container (using sudo)
          # This command loads your secrets from /home/ubuntu/MedVault/.env
          sudo docker run -d --name medvault --env-file .env -p 80:5000 medvault
        EOF
