    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          # Clone repo if missing
          if [ ! -d "/home/ubuntu/MedVault" ]; then
            git clone https://github.com/yasvanthrajan/MedVault.git /home/ubuntu/MedVault
          fi

          cd /home/ubuntu/MedVault
          git pull origin master

          cd backend

          # Stop/remove old container if exists
          docker stop medvault || true
          docker rm medvault || true

          # Free port 5000 if any container is still using it
          docker ps -q --filter "publish=5000" | xargs -r docker stop

          # Build using backend/Dockerfile
          docker build -t medvault -f Dockerfile .

          # Run new container
          docker run -d --name medvault -p 5000:5000 medvault
        EOF
