name: Deploy MedVault Backend to EC2

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          cd ~/backend
          git pull origin main
          docker stop medvault || true
          docker rm medvault || true
          docker build -t medvault .
          docker run -d --name medvault --env-file .env -p 80:5000 medvault
        EOF
